### ISSUE TITLE
Exam Issues: Helicopter Operations Exam

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#13]
# Question 5

> Aspiring UX-152 pilots should be able to?
- [x] Answer B should be changed to "Fly the aircraft safely" for grammatical correctness
- [x] Answer C should be changed to "Operate an M16 Rifle effectively as a rifleman" to reflect the migration to RHS

![image](https://cloud.githubusercontent.com/assets/11630560/6879910/40af99e4-d4ea-11e4-9d5e-f68392019e63.png)
# Questions 8, 9
- [x] Remove dummy/placeholder questions(?)

![image](https://cloud.githubusercontent.com/assets/11630560/6879914/69dbc9a0-d4ea-11e4-97be-6eb9b0a16273.png)
![image](https://cloud.githubusercontent.com/assets/11630560/6879915/758b3fba-d4ea-11e4-8ee8-8cf492596f31.png)
# Question 13

> The Loadmaster is responsible for:
- [x] Answer A should be changed to "The passengers and cargo" for grammatical correctness

![image](https://cloud.githubusercontent.com/assets/11630560/6879917/b5255610-d4ea-11e4-991c-ba2e5dca5cd3.png)

**Comment by jonpas** [comment]
All fixed. Had to change indexes of all questions after 7 due to removal, I guess I know someone was lazy!

**Comment by jezalenko** [comment]
<starts whistling>
