### ISSUE TITLE
Modify Veteran Difficulty on servers

### ISSUE THREAD

**Issue by SamuelMaunder** [usecforce/USEC_IssuesWiki#15]
- Disable "[This Unit] was killed"
- Disable Scoreboard

**Comment by Marstruc** [comment]
Code for scoreboard = "netStats = 0" in the server profile

**Comment by jonpas** [comment]
Thanks, might need that for proper setup (since TADST doesn't generate new config as it would overwrite Headless Client setup).

**Comment by jonpas** [comment]
Finished as part of 0.9.0.
