### ISSUE TITLE
Remove Binoculars from all non SL loadouts

### ISSUE THREAD

**Issue by ghost** [usecforce/USEC_IssuesWiki#17]
Raised by Vuk on TS. All loadouts have binos included, which leads to people standing out in the open looking through binos. We should reserve them for SL+ as these are the more experienced people who actually require them and are more tactially aware. (we never used to have binos for the troops for this exact reason).

**Comment by jonpas** [comment]
Those lemmings... 

What about TLs?

**Comment by ghost** [comment]
I support TLs can retain them. @SyMP2005?

**Comment by bonnielunawalker** [comment]
Agreed Stark, perhaps JTACs and radio operators should keep them too,
though that can probably be decided on a mission-by-mission basis.

**Comment by ghost** [comment]
JTACs will _definitely_ need them, maybe ROs as well (although the role is kinda the same at the moment). JTACs should have either the Laser Designator or the Vector IV, depending if they're playing with CAS or arty.

**Comment by DavidCamre** [comment]
Binoculars, Rangefinders Laser Designators or equivalent is already part of the chronos gear that Rory put in the crates. There's no need / reason to have it as part of the automatic "free" loadout. 

Those who needs the binoculars or better should manually pick it out of the crates similar to optics etc.

**Comment by MattLightfoot** [comment]
Agreed with david, ideally I think we should keep the automated loadouts as few as possible.

**Comment by ghost** [comment]
I agreed with both of you, hence why I'm asking for bino to be removed from the automated loadouts :)

**Comment by bonnielunawalker** [comment]
Perhaps to eliminate people taking them unnecessarily they could be kept in
UCOM crates. That way you could ensure only people who need them are taking
them.

The obvious downside to that is that Matt is so protective of his crates he
may have an anurism.

**Comment by MattLightfoot** [comment]
Maybe we have a second SQL crate then, with them in, as people keep taking stuff from the UCOM crates, as the 501 doesn't have any left and that doesn't remedy the issue.

Either way that can be something we can tackle properly post Op Anvil

**Comment by DavidCamre** [comment]
Maybe split up UCOM and Squad leader crates?

UCOM crates are literally just for ucom. It's mainly hats and stuff that Matt has licked.

Squad lead objects are more available but it can create confusion if you have two crates next to eachother and they're told to take from one but not the other. Simple fix is to move the UCOM stuff in a separate room and crate.

**Comment by bonnielunawalker** [comment]
That sounds like a better fix David. You're right that there's no need to
give more people an excuse to raid UCOM's stuff.

**Comment by DavidCamre** [comment]
It's not because people are trying to steal from ucom but there's no way for someone to know what stuff is UCOMs and what stuff is free for them to take if it's all lumped together :)

**Comment by MattLightfoot** [comment]
http://vignette1.wikia.nocookie.net/clubpenguinpookie/images/3/32/Grumpy_Cat_Good.jpg/revision/latest?cb=20140306235947

**Comment by ghost** [comment]
I have to share a crate with Matt? Ewww, I don't want the stuff he's licked!

**Comment by jonpas** [comment]
Ok that's settled for template then, I'll verify that binos aren't actually in presets. And remove them from training for non-SL.

**Comment by jonpas** [comment]
Removed Binoculars from Rifleman and AA/AT gear on Training map. Template (Chronos) doesn't have any included, I double checked.

As of now we don't have separate RO/JTAC loadout as it's not necessary for Training map in my opinion. And for Template (Chronos) base gear is the same.

**Comment by jonpas** [comment]
Done in 0.9.0.

**Comment by DavidCamre** [comment]
It should be removed from any and all loadouts of chronos maps. Binoculars are provided through the crates.

**Comment by jonpas** [comment]
> Template (Chronos) doesn't have any included, I double checked.
