### ISSUE TITLE
Update Recruit Welcome Message

### ISSUE THREAD

**Issue by bonnielunawalker** [usecforce/USEC_IssuesWiki#19]
Per the changes to the way recruit transit will be working (namely that SQLs will now have to contact new recruits, not the other way around) I have written an updated welcome message. https://docs.google.com/document/d/1M5h-YZyXavwFM0f-1WzzPAzChngzj6K-2X7ybomt3vk/edit?usp=sharing

Is someone able to update it on the website?

**Comment by codethirteen** [comment]
Fixed in Master, need to test before pushing to release.
