### ISSUE TITLE
Come up with training plan for UX152

### ISSUE THREAD

**Issue by MattLightfoot** [usecforce/USEC_IssuesWiki#2]
Create a training plan for UX 152 based around;
Junior Airman,
Airman,
Senior Airman.

**Comment by MattLightfoot** [comment]
Referenced in this weeks meeting, UX152 to have a meeting this week to progress this.

**Comment by jonpas** [comment]
Considering closed as Doe's training is already being used and is written (just needs double checking, few fixed and it's ready to go) and this issue says "come up with", so we did! :grin:
