### ISSUE TITLE
Marking members of recruit transit with their location

### ISSUE THREAD

**Issue by bonnielunawalker** [usecforce/USEC_IssuesWiki#20]
Is it possible to denote members of the Recruit Transit squad as being from certain regions? i.e. 'John 'Smithy' Smith - EU'. This would make it a lot easier for SQLs and 2ICs to identify new recruits that will be entering their squads and attending their training sessions.

If this isn't possible, I suggest creating a spreadsheet of recruits and locations that gets updated whenever a new member joins or leaves recruit transit. I'm willing to set this up and maintain it.

**Comment by MattLightfoot** [comment]
This _could_ be done with the titles method however it would require manually assigning it and more people given Database access.

**Comment by bonnielunawalker** [comment]
Would a manual spreadsheet be better? As I said, I'm happy to maintain it, but I thought there might be an easier way.

**Comment by MattLightfoot** [comment]
That I know of yes but it may be best to get @codethirteen and @jonpas 's feedback.

**Comment by jonpas** [comment]
We can do if in that squad show location in title (like billet is I guess). The issue is that recruit transit ia just renamed command squad at this moment and is same in all units.

**Comment by bonnielunawalker** [comment]
Sounds like it's more trouble than it's worth honestly...

I've knocked together a spreadsheet. If you guys think this is more efficient, I'll send it out to SQLs and the recruiting directorate.

https://docs.google.com/spreadsheets/d/1SNPZfQAmwp0-vhxWUEp80gUMw9yp3UGw1KacavLHAvs/edit?usp=sharing

**Comment by Omnirock** [comment]
When I was SQL for EU2,  we had spreadsheets for training with members assigned to their locations, can we not adapt that for use maybe?

**Comment by bonnielunawalker** [comment]
We still have that, but it's already reasonably crowded. I'll send this new spreadsheet out today.
