### ISSUE TITLE
Dealing with trolls

### ISSUE THREAD

**Issue by bonnielunawalker** [usecforce/USEC_IssuesWiki#23]
We've had some issues over the past days with trolls (one guy in particular). I've thought of some potential solutions.

The first is making supplying a Steam profile a prerequisite for applying for USEC. We could state on the application page that all applications without a Steam profile will be automatically rejected. This will add another layer of complexity to trolling efforts, and allow us to more easily see who is serious about joining. This morning, I mistakenly rejected an application from a friend of a member because I thought he was a troll. A Steam profile would make it easier to identify repeat trolls.

The second is simply giving recruiters TeamSpeak moderator privileges. Being a recruiter, I obviously have a vested interest here, and it's totally UCOM's call, but it would certainly make dealing with trolls considerably easier.

**Comment by MattLightfoot** [comment]
I'm happy on  both, what's your take @jezalenko ?

**Comment by Omnirock** [comment]
Not sure if this was the troll or not, but there was a user named "Jet Fuel Doesn't Melt Steel Beams".

**Comment by bonnielunawalker** [comment]
Very likely the same guy we've been dealing with. He keeps using VPNs to bypass TS bans. It's actually pretty impressive the efforts he's going to.

**Comment by SyMP2005** [comment]
Good ideas imo.

**Comment by ghost** [comment]
Looks like you're a TS mod once again @brynwalker. I also agree with the Steam profile, however we're also going to need to verify that profile somehow, to prevent him from putting in anything to get the profile to work.

**Comment by bonnielunawalker** [comment]
The Steam alias he was using was "Streamy". I guess for the next few
days/weeks we double check all steam profiles to see if any of them were
once called Streamy. No doubt if he tries again he'll rename his account.

**Comment by jonpas** [comment]
I can make the Steam ID required, meaning it won't let you put in the application if it's not filled out, can also limit it to 17 characters (probably) as Steam IDs are.

**Comment by bonnielunawalker** [comment]
Awesome, sounds great JJ! I'll assign you :)

**Comment by jonpas** [comment]
I made an internal ticked in Website repository, I am not dealing with trolls, thank you! :D

**Comment by bonnielunawalker** [comment]
Fantastic, thanks!

**Comment by ghost** [comment]
I also spoke to my brother who works in IT last night - a novel solution could be using a cookie modified from a targeted advertising role to track users. If the troll changes IP address, we can still block them based on their unique cookie. Thoughts?

**Comment by SyMP2005** [comment]
I like it @jezalenko, 

I thought for trolls joining teamspeak, as they would be civilians, maybe we can set a minimum rank requirement of PVT to join other channels? The troll will be stuck in lobby then when he joins.

**Comment by bonnielunawalker** [comment]
Good plan. The only downside I see is that if a civvie who actually wants
to become a member joins and there's no admin on to move him to the mess,
he'll be stuck there and won't be able to talk to anyone.

**Comment by SyMP2005** [comment]
I do believe that these days there is almost always a 2IC / senior member with TS mod around. I wouldn't worry too much about that.

**Comment by MattLightfoot** [comment]
I think we should set minimum rank to everything apart from lobby, the mess and recruiting. So if some knob joins everyone just jumps down to another channel. Whereas if it's a recruit they can jump right in.

**Comment by bonnielunawalker** [comment]
Sounds reasonable, as long as we have an adequate Lobby description or
welcome message telling people which channels they can join if they're not
members.

**Comment by jonpas** [comment]
> I also spoke to my brother who works in IT last night - a novel solution could be using a cookie modified from a targeted advertising role to track users. If the troll changes IP address, we can still block them based on their unique cookie. Thoughts?

Our website doesn't use any cookies at all: http://www.usecforce.com/privacy.asp
We are allowed to use them apparently though, but I have no idea how to work with cookies or anything.

I agree with restricting less than PVTs to only those 3 channels. And what Bryn said, proper notice for them.

**Comment by Omnirock** [comment]
I agree with the TS restrictions, there really is no reason for guests to have access to much more than the lobby. 

I know the mess hall is sort of an off-topic channel, but I'd rather not have potential "guests" come in and mic spam or start streaming music or whatever sort of nonsense people come up with. 

On cookies: 
- How does this work if your browser is set to delete cookies on exit? 
- Third Party cookies blocked?
- Cookies not accepted at all in settings?
- Browsing with a mobile device that rarely uses cookies anyway? 
  
  I really don't see it as much of a solution, or worth the effort in implementing it. 

The Steam verification process should be more than enough to keep but the most dedicated trolls out. Having to create e-mails AND Steam accounts just to sign up to Troll isn't worth the effort for most people. 

More information on the Steam API and OpenID sign can be found here: 
http://steamcommunity.com/dev

**Comment by jonpas** [comment]
We could use PHP OpenID, but our website still runs almost fully in ASP. For starters I was thinking simply add Player ID to the application (that's basically Arma 3 ID which is equivalent to Steam ID64) and check if it's 17 characters long. Then later on we can do a check through OpenID I guess.

BTW, Steam ID that is currently in the application and profiles is NOT the Steam ID I am talking about here. The on on application is basically just a link to the Steam profile (custom profile URL which can be set on Steam), it might be better if we rename that. Right now on the website they are distinguished as Steam ID = custom profile URL and Player ID = Arma 3/Steam ID number.

**Comment by Omnirock** [comment]
Curious, how many developers do we have in USEC familiar with ASP?

**Comment by jonpas** [comment]
None. :grin: 
It's me and Paul primarily trying to do shit with it.

**Comment by MattLightfoot** [comment]
trying and succeeding so far :palm_tree:

**Comment by bonnielunawalker** [comment]
Yep, I saw what looked like someone from another group attempting to join
TS today. No doubt he was another guy trying to steal members. He got stuck
in the Lobby and gave up ;)

**Comment by MattLightfoot** [comment]
Which group do you know bryn, RG or CIA? as they could have been looking for me mate

**Comment by bonnielunawalker** [comment]
It may have been CIA, I didn't really take note of the name I'm afraid.

**Comment by bonnielunawalker** [comment]
Just saw him on the online TS tracker again, his name was SSGT A.Reign.
Ring a bell at all?

**Comment by MattLightfoot** [comment]
This is McClean chap he's one of us just wrong TS name

**Comment by bonnielunawalker** [comment]
Ah, okay, makes sense now :P
