### ISSUE TITLE
Suggest Award page formatting

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#24]
The submitted text is all wonky on the suggest award page

![image](https://cloud.githubusercontent.com/assets/11630560/7002648/33136368-dc1c-11e4-9e58-cf3bdb0cf793.png)

**Comment by codethirteen** [comment]
Your screenshot shows the recommend award page. That page has been fixed on our devbuild, it'll be pushed out in our next release. 

If you somehow got there from the comrep submit page then let us know!

**Comment by assaultboy** [comment]
You're right
I need more sleep.

**Comment by codethirteen** [comment]
No problem, thanks for all your reports!
