### ISSUE TITLE
SGTMAJ/F sorted before officer ranks

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#27]
On the [roster](http://www.usecforce.com/roster/) Sam Maunder is listed before even the officers. It is my understanding that the roster is listed from highest ranking to lowest.

I believe SGTMAJ/F is a lower rank than any officer rank thus Sam should be below the officers.

**Comment by jonpas** [comment]
Already known, but thanks!

**Comment by SamuelMaunder** [comment]
I see no problem with this...

> Assign Self
> Close as "Non-fix"

**Comment by jonpas** [comment]
It's not a priority, let the lemmings know who is the boss around them (grooming standards, yay!). :grin:

**Comment by assaultboy** [comment]
Oh god. Don't encourage Sam.

**Comment by codethirteen** [comment]
I'm not around the database right now, but the file is sorting the table like so:

`ORDER BY Member_SUB_Rank.RankOrder DESC`

So it appears we can change the SGTMAJ/F RankOrder in the database and it will rectify this issue.

**Comment by jonpas** [comment]
Yep, changed it to level 9 (same as other 2 SGTMAJ ranks are) and it fixed it. Does it matter on which position it is on [ranks page](http://www.usecforce.com/personnel/ranks.asp) though? As that just moved it downwards, easy fix is we just change level to something like 9.1 (as we did for Airman ranks) as going to 10 and up moves it to position 1.0, freaking weird.

**Comment by codethirteen** [comment]
Yeah the order is correct, but we need to add 9.1 to make it appear at the top of all SGTMAJs.

**Comment by jonpas** [comment]
Done, but of course the website gets the location of it through the RankOrder, so instead of duplicating the images I made symbolic links, I'll do the same for anything else duplicate I find.

@Karnax1507 is no longer the boss. Sorry mate!

**Comment by ghost** [comment]
This fix has changed Sam's rank picture. Before he had three stars in his picture, now he has one. I believe that the rank order in the database corresponds to the picture.

**Comment by jonpas** [comment]
Yep, I thought it was not the same! I'll fix it when I get home. But yes, RankOrder in database corresponds to picture name as you said.

**Comment by jonpas** [comment]
Fixed.

**Comment by SamuelMaunder** [comment]
:-1:

**Comment by jonpas** [comment]
You know that no rank can oppose me. ;)

**Comment by MattLightfoot** [comment]
"Allegedly"

**Comment by jonpas** [comment]
We all know you don't want a proof. :grin:

**Comment by SamuelMaunder** [comment]
![jj logo](https://cloud.githubusercontent.com/assets/11335311/7050067/9dc8f460-de16-11e4-84f2-9f954a01955f.jpg)

JJ put this on the USEC Homepage

**Comment by jonpas** [comment]
Don't make me sue you for using my custom made images in anything not made by me!

**Comment by ghost** [comment]
Thanks JJ, we all now know the officer corps is superior :D
