### ISSUE TITLE
Squad Leader tag below name on unit roster

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#28]
The squad leader tag on the [unit roster](http://www.usecforce.com/roster/?g=Unit) page is below the holders name.

This conflicts with the alignment of every other tag which is to the right of the holders name.
I'm assuming this is not intended, but if it is I recommend changing it to fit with the styling of the other tags.

**Comment by jonpas** [comment]
Can you supply a screenshot of how it conflicts with the alignment?

**Comment by assaultboy** [comment]
Not home right now, I'll take one when I get home.

It's also not "broken" it's just different from every other tag

**Comment by jonpas** [comment]
Yep I know, hence why I labeled it with enhancement. ;)

**Comment by assaultboy** [comment]
Here are some examples. Notcie how the tag is below Vuk's name
![image](https://cloud.githubusercontent.com/assets/11630560/7028354/5f443d24-dd23-11e4-8d0c-504a8fff4cfb.png)

But in these pictures the tags are to the right of the name
![image](https://cloud.githubusercontent.com/assets/11630560/7028372/7561204a-dd23-11e4-9d26-5bcc2b2612b8.png)
![image](https://cloud.githubusercontent.com/assets/11630560/7028376/7c4f4cba-dd23-11e4-83ef-0ecd9bbf31cc.png)
![image](https://cloud.githubusercontent.com/assets/11630560/7028380/877f65a2-dd23-11e4-8533-d531c4eec40a.png)

**Comment by jonpas** [comment]
Yep that's exactly due to Squad Leader position being from old system, title next to the name is as well, but Squad 2IC is from new system (as much as I know). I do believe having Squad Leader below name makes it look better though, can differentiate with everyone else easier.

**Comment by codethirteen** [comment]
Fixed in dev. This will be pushed in the next update. As an aside, if we assign classes to everything where possible, rather than hardcoding in linebreaks, etc., we can more easily fix this with pure CSS and then we don't have to worry about old/new systems.

**Comment by jonpas** [comment]
I suggest to revert this, 2 reasons:
- Conflicts with titles next to name, eg. Joel Restrepo has both Squad Leader and First Sergeant UX501 and it looks bad (look on dev page @codethirteen )
- Looks better on a separate line, makes it clearer to see who is the squad leader in my opinion

I think we should instead look into moving Squad 2IC below name as well, again we come to Squad Leader title using old system and Squad 2IC the new one though.

**Comment by jonpas** [comment]
@codethirteen bump (read above comment)

**Comment by codethirteen** [comment]
Sure we can revert this, it was just a `<br>` tag.

**Comment by codethirteen** [comment]
```<br> tag

**Comment by jonpas** [comment]
If you agree, yes, I am not trying to be dictator here. :grin:

**Comment by codethirteen** [comment]
Thinking about it, it will be better to not put a `<br>` tag back in, but to give it a CSS class instead. If we do that with the old and the new tag systems we can style both much easier, and you can use CSS to target `::before` to add the `<br>` if we want it. Much easier to maintain...

**Comment by jonpas** [comment]
Yep I agree!

Also, one line code is written in markdown like:
- backtick code backtick

Multiline:
- 3x backtick
- code
- 3x backtick

**Comment by codethirteen** [comment]
Yeah I wrote that on my phone. Funny thing now I edited it from desktop browser it still looks screwed up.

**Comment by jonpas** [comment]
Heh weird!

**Comment by codethirteen** [comment]
What differences are there in the old and new systems? I'm wondering how hard it would be to make them all part of the same system. This is yet more spaghetti we have to untangle!

**Comment by jonpas** [comment]
Not sure, I haven't looked into it any more.

**Comment by jonpas** [comment]
This has been done in 2015.05 update.
