### ISSUE TITLE
Remove OP Phoenix flights

### ISSUE THREAD

**Issue by codethirteen** [usecforce/USEC_IssuesWiki#3]
http://www.usecforce.com/operations/

There are two remaining flights from an old mission sitting there awaiting tasking. I filed a dry PIREP on one to remove it, but it would be better to do this from the admin side.

**Comment by jonpas** [comment]
Assigning to @MattLightfoot since he is listed as Director of Operations.

**Comment by ghost** [comment]
I've deleted the flights from the backend, can you please confirm that they're all gone/fixed?

**Comment by jonpas** [comment]
Yep, all good. Thanks Stark!

**Comment by ghost** [comment]
No worries!
