### ISSUE TITLE
Broken Link in Footer

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#31]
In the footer of every page there is the little copyright Dean Hall Design thing

![image](https://cloud.githubusercontent.com/assets/11630560/7028571/ab446b76-dd24-11e4-9fa4-f6317a42457a.png)

The Dean Hall Design link brings you to a [forbidden access](http://www.dhd.co.nz/) page.

I don't know if there is really anything that can be done about this one, but I thought I might as well post it anyway.

**Comment by jonpas** [comment]
That website is probably just not existing anymore, we'll do something about it.

**Comment by codethirteen** [comment]
Fixed in dev. Will get pushed with our next update.
