### ISSUE TITLE
Primary weapons are not displayed in the inventory

### ISSUE THREAD

**Issue by AGroupOfBears** [usecforce/USEC_IssuesWiki#32]
Primary weapons in the players inventory is invisible, it cannot be click and dragged, but right clicking still removes the weapon from the inventory, the position of the bipod attachment slot is also skewed and some weapons do not function at all because the magazine will not be placed in the weapons magazine slot.

The issues is coming from AGM_Inventory.bpo/Config.bin/RscDisplayInventory.hpp.

as far as I can see, RscDisplayInventory.hpp changes the scaling from the users interface size to a  static size.

Removing RscDisplayInventory.hpp from within the config.bin fixes the issue.

**Comment by jonpas** [comment]
This started happening with Arma 3 Update 1.42 (Marksmen DLC) I guess? 

Thanks for the fix steps!

**Comment by AGroupOfBears** [comment]
Yes, this started with the 1.42 update.

**Comment by jonpas** [comment]
Will fix, probably easiest to remove that PBO for now due to ACE incoming, all it does is change inventory UI size and items list. Possibly before this week's force-wide, if I'll have time.

**Comment by jonpas** [comment]
Fixed for 0.9.1 in jonpas/AGM@a3810d42723c3680ddd56f1ddebf2fc58bb59a52
