### ISSUE TITLE
Modpack Issue

### ISSUE THREAD

**Issue by Dabclipers** [usecforce/USEC_IssuesWiki#34]
I have been gone for about 5 weeks as of April 10th.  I planned to participate in the April 9th fundamentals training after I updated my Arma3Sync to the new autoconfig I haven't been able to join a server.  When I try to join the server through Arma3Sync I get the following message:

Failed to Launch Arma 3
The following selected addons are missing:
@c17a3;@USEC_LHD;@taw_viewdistance

My Usec name is PFC J.Ryan

**Comment by jonpas** [comment]
It probably said "missing server addons", as we are not using either of those anymore. Recheck what mods you are running.

**Comment by Dabclipers** [comment]
Deleted them from my modpack, thats weird that it kept installing.

**Comment by Dabclipers** [comment]
Ok, just tried joining and while it will start Arma now the server keeps autokicking me when I try and join.

**Comment by jonpas** [comment]
Resolved over TS. The issue was improper modpack selected (probably due to repository host change, left-over info).
