### ISSUE TITLE
Add more games to gaming information

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#35]
Currently each profile has a Gaming Information area:

![image](https://cloud.githubusercontent.com/assets/11630560/7108350/654d44d6-e151-11e4-8374-6714d79f9ba3.png)

When I joined it had three entries: Arma 2, Arma 3, and FSX.
I imagine when there were multiple games USEC operated in it was useful but as of now since we only use Arma 3 I don't really see it's purpose (Unless it does something in the back end I'm unaware of)

My suggestion is maybe add some games that are popular within USEC such as War Thunder, DCS, Insurgency, etc. To serve as a reference when trying to get a party going in those games.

**Comment by jonpas** [comment]
That requires more database entries, I vote against. We are an Arma community, if people want to know who has what, they can ask.

**Comment by atlasicus** [comment]
I have to agree with JJ; the primary usage of that is to help upper command to gauge how many people owned each game for missions and operations back when both Arma 2 and Arma 3 were still both active games for the force.  Popularity of additional games rise and fall over time. It might be a good idea to start a forum thread along the lines of "What are you playing currently?" in the appropriate forum to help people coordinate.

**Comment by assaultboy** [comment]
Well if the area won't be modified to include other games then maybe it has outlived its purpose?

**Comment by jonpas** [comment]
No, it's there for recruits, they must own Arma 3 to be accepted. Being there on the list doesn't do anything to anyone, or does it? Adding more is no point, we do not want our database to have thousands of games in, and even less do we want to be adding them.

**Comment by assaultboy** [comment]
I understand that. But I assume anyone who joins should have Arma 3. I guess I'm just confused as to why it's still displayed and editable on the profile post application/recruitment

**Comment by codethirteen** [comment]
@assaultboy, I think the primary argument to keep it is because we may in the future adopt other **official** platforms, and trimming features from the website that may be useful in the future just means we have to reinstate it in the future. obody wants to do extra work on a volunteer basis, with so much else to do.

I see your point though, it does currently look out of place and we could probably create a backend view for unit admins, but it's not harming anyone the way it is currently so I vote to leave it as-is.

**Comment by jonpas** [comment]
Recruitment, it's obvious as I said, for all ozher pages, why not? There is really no point removing it.

**Comment by jonpas** [comment]
Closing as votes were in favour of not changing it, feel free to keep discussing.
