### ISSUE TITLE
Remove Op Witchcraft Sub forum

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#36]
In the current operations sub-forum there is a Op Witchcraft area.

I don't know if that's queued up for later but it's not a current op so it should probably be removed?

**Comment by jonpas** [comment]
We don't know yet, might get renamed, might not. We'll leave it as is for now.

**Comment by MattLightfoot** [comment]
This was a very old operation for FSX that was planned but never pulled off, I've just shifted it to archived ops

**Comment by jonpas** [comment]
Ok, apparently we will!
