### ISSUE TITLE
M14 olive/camo no long fully automatic

### ISSUE THREAD

**Issue by AGroupOfBears** [usecforce/USEC_IssuesWiki#37]
Don't know if this is a bug or intentional, but the M14 added in the 1.42 update is not fully automatic.

In vanilla Arma the M14 is full auto, when running the USEC mods, it isn't.

**Comment by jonpas** [comment]
Do you mean the vanilla [Mk18 ABR 7.62 mm](https://community.bistudio.com/wikidata/images/0/0d/Arma3_CfgWeapons_srifle_EBR_F.jpg)?

**Comment by AGroupOfBears** [comment]
No, the Vanilla MK14 Olive or Camo rifles that were added in the Marksman 1.32 update

![2015-04-15_00001](https://cloud.githubusercontent.com/assets/11863608/7142004/8b68bb82-e318-11e4-999a-0167be2c76a6.jpg)

-EDIT-

Disabling ASR AI turns allows the MK14 to switch to full auto again.

Also, the MK14 was able to be switched to full auto before the USEC 0.9.1 Update.

**Comment by jonpas** [comment]
Ok, can you try disabling mods one by one (or whatever the dependencies are, Arma will tell you at start). I suggest start by disabling AGM, then go with what you think fiddles with it.

**Comment by AGroupOfBears** [comment]
I disabled the mods one by one and found that disabling ASR seems to fix the issue.

-EDIT- I unpacked the asr_ai3_main.pbo and nothing seems to reference the MK14. I have no idea what's causing it, mostly because ASR controls AI and shouldn't control weapon fire modes.

If I had to guess, I would say it's something in script_Weapons.hpp, or ing CfgWeapons.hpp inside config.bin.

Also the MK-1 EMR is also not able to be switched the fully automatic either.

**Comment by jonpas** [comment]
Interesting, can you report it to [ASR AI 3 BI forums topic](http://forums.bistudio.com/showthread.php?173515-Asr-ai-3)? Include we are using latest 0.9.19 version with latest RHS optional config. Thanks!

**Comment by jonpas** [comment]
Thanks! Reference: http://forums.bistudio.com/showthread.php?173515-Asr-ai-3&p=2921242&viewfull=1#post2921242

**Comment by jonpas** [comment]
Marking invalid as it's not our fault.

**Comment by jonpas** [comment]
Fixed on their side: http://forums.bistudio.com/showthread.php?173515-Asr-ai-3&p=2922383&viewfull=1#post2922383

Need to make a label for third party mod issues. :grin:

**Comment by jonpas** [comment]
Please reopen if not fixed with next modpack update. Thanks!
