### ISSUE TITLE
Coding Guidelines update

### ISSUE THREAD

**Issue by jonpas** [usecforce/USEC_IssuesWiki#38]
@DavidCamre @MattLightfoot @Daishiknyte @atlasicus @codethirteen @jezalenko @SyMP2005 @Takelmeifter @Omnirock @Karnax1507 @brynwalker 

[Coding Guidelines for Arma 3](https://github.com/usecforce/USEC_General/wiki/Coding-Guidelines-%28Arma-3%29) received an update! Our guidelines are getting changed for the new standards, adapting from [ACE3's Coding Guidelines](http://ace3mod.com/wiki/development/coding-guidelines.html), to make coding for Arma more simple and universal.

Highlighted changes:
- [Indentation to 4 spaces](https://github.com/usecforce/USEC_General/wiki/Coding-Guidelines-%28Arma-3%29#indentation) (from previous 2) - please change your editor settings accordingly
- [Function header](https://github.com/usecforce/USEC_General/wiki/Coding-Guidelines-%28Arma-3%29#functions)

No rush in changing either, just keep it in mind for whatever you do from now on, old things will get changed over time (or not).

**Comment by SyMP2005** [comment]
I AINT CODING SHIT BRO! :(

**Comment by jonpas** [comment]
Closing as it's almost been 1 month since this announcement.
