### ISSUE TITLE
Updating recruit exam

### ISSUE THREAD

**Issue by bonnielunawalker** [usecforce/USEC_IssuesWiki#39]
I've drafted some updates for the recruit exam. Since I'm not in the training billet I didn't actually want to commit the changes before consulting others. Most changes are wording or grammar, but one or two questions have had content changed slightly.

Q1.
Changed wording for clarity - “What is USEC’s full name?”

Q2.
No change.

Q3.
Added quotation marks to answer D. - “An organisation with ranks, where you must call everyone of a higher rank ‘sir’.”

Q4.
No change.

Q5.
No change.

Q6.
Wording was a little confusing, so it's been updated - “How often does each squad conduct training sessions?”

Q7.
As above, changed for clarity - “How many missions and/or training session must you attend every month, at a minimum?”

Q8.
Changed question from "what should you do" to "who should you contact?" format. Since the exam is equally about teaching as testing, I felt this would drive the point of this question home more - “Who should you contact if you cannot attend the required number of training or force-wide sessions?”
Answer A - “No one”
Changed all answers to remove ‘informed’.

Q9.
Updated question for grammar - “How often does USEC conduct operations?”
Answer A slightly changed for clarity - “4 per year, or every 3 months”

Q10.
No change.

Q11.
Changed question wording. - “Which position has overall command over USEC?”

Q12.
Added 'main' to question, since there are two infantry units in the answer (both Ghouls and Lancers) - “What is USEC’s main infantry unit?”

Q13.
No change.

Q14.
No change.

Q15.
This question is confusing, but necessary. I added 'This is not a trick question' at the end to make it more clear. - “You have just passed an exam, but you feel you could have done better What can you do? <b>The answer is B. This is not a trick question.</b>”

As soon as someone from training gives this the go-ahead, I'll update them on the website. I just wanted to make sure you guys agreed with updating it. Feel free to suggest changes.

**Comment by jonpas** [comment]
Next time do... @SyMP2005 @MattLightfoot @jezalenko ... etc. to summon them! :grin:

**Comment by assaultboy** [comment]
I'm not a fan of Q15 just giving away the answer. I understand that the exam is supposed to teach but it is also supposed to test that the recruit has read what he has been given to read. So the answer should be given in the recruit literature instead of on the exam.

Though I'm not establishment so who gives a damn what I think.

**Comment by jonpas** [comment]
I agree, Q15 should probably just be removed if no good replacement is found.

**Comment by ghost** [comment]
I'm fine with removing Q15 _if_ we have some method of communicating that info - maybe we could add a bit in the recruit presentation, and change the question to test if they've read that bit?

**Comment by jonpas** [comment]
> if we have some method of communicating that info

What do you mean?

**Comment by ghost** [comment]
Currently, the only way the tell new people that you can't do an exam more than once (and get a fuck-ton of ribbons) is through this question. I think it's still an important bit of info to tell new people. By removing this question, we are not telling newbies this info in any way.

**Comment by jonpas** [comment]
Ah, maybe I should fully read what the question currently is! -.-

**Comment by bonnielunawalker** [comment]
Yeah, I'm agreeing with Stark. I know we're giving away a free answer, but
I can't really think of a better, more direct way to convey the information.

**Comment by SamuelMaunder** [comment]
Maybe put a big warning on the Training page where all our exams are all big and red which shows the info. If they miss it then they have zero excuse

**Comment by jonpas** [comment]
Or Stark finishes his feature which hides already-finished exams. :grin:

**Comment by bonnielunawalker** [comment]
Oooh, sounds fancy ;) I might leave it in for now, it's served us pretty
well so far. When Stark finishes that up I'll remove it and replace it with
a more relevent question.

Out of town right now, but when I get home I'll update the quiz if there's
no other objections :)

**Comment by bonnielunawalker** [comment]
Edited the exam to include the updated material.

**Comment by jonpas** [comment]
:+1:

**Comment by ghost** [comment]
Cheers mate.
