### ISSUE TITLE
Arma Crashes when adding M4 with M320 to a unit

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#40]
The RHS weapon M4 (M320) Classname : rhs_m4_m320 causes the client to crash then a local unit is given the weapon.

This would explain why people crash when loading the squad leader role on the server.

EDIT: The M4A1 (M320) Classname : rhs_m4a1_m320 also cause theclient to crash.

**Comment by SyMP2005** [comment]
> rhs_weap_m4_m320

They still have to update that on their website...

**Comment by jonpas** [comment]
Yes, the classname has been changed as @SyMP2005 said, it's been noted in their (very long) changelog. I've already fixed it for the Training mission on dev. AFAIK, we don't have any M4A1s with M320s on the Training server, so that should be fine, can you confirm?

**Comment by jonpas** [comment]
This has been fixed as far as I am aware.
