### ISSUE TITLE
Chris 'Howitzer' Howie has 14 Advanced Operations Ribbons

### ISSUE THREAD

**Issue by bonnielunawalker** [usecforce/USEC_IssuesWiki#41]
Might want to remove them. No idea why anyone would want to sit that exam 14 times, but apparently he did...

Paging @jezalenko.

**Comment by jonpas** [comment]
~~ID?~~ Nevermind...

**Comment by jonpas** [comment]
Cleaned Ribbons and both Decoration and Exam history.

Feel free to close @brynwalker if that's all (if anything is to be done it should be handled through private channels, this here is public).

**Comment by bonnielunawalker** [comment]
No problem, closed.

**Comment by ghost** [comment]
Jeezus. 14?

**Comment by bonnielunawalker** [comment]
Yup. To be fair, his profile looked awesome :P
