### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by codethirteen** [usecforce/USEC_IssuesWiki#42]
Post missing images here.
- [x] http://www.usecforce.com/images/Ribbons/citationforcecommander_no2.png

**Comment by jonpas** [comment]
Fixed all those, forgot to relink symlinks with new PNGs! :grin:

**Comment by codethirteen** [comment]
Some more:
- [x] http://www.usecforce.com/images/parchment2.png (Broken on promotion MyMails)
- [x] http://www.usecforce.com/images/courses/land_tactics_basic_mb.png (found broken in [forum promotion thread](http://www.usecforce.com/forums/showthread.php?tid=6074))
- [x] http://www.usecforce.com/images/courses/qual_land_t3_mb.png
- [x] http://www.usecforce.com/images/badges/usec_infantry_mb.png

**Comment by jonpas** [comment]
Found one more:
- [ ] Promotion/Award Advisory MyMail background

**Comment by jonpas** [comment]
FIxed parchment, last 3 images didn't even exist in GIF, this is weird. They are supposed to be the same as the non-`_mb` counterparts, it'd be best if we can clean that up in code directly, I'll make symlinks now, feel free to open another issue in website repo to change in code and remove them afterwards.

**Comment by jonpas** [comment]
Looks like all fixed for now, if there are more, reopen the issue.
