### ISSUE TITLE
Non-NCO in NCO group on forums

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#45]
On the User Control panel it shows me as in a NCO group when I'm not an NCO. I don't actually know what difference this makes or if it's intentional.

![c4bf758faee4e440b7a6c8c88004e3f7](https://cloud.githubusercontent.com/assets/11630560/7621565/c3c5e688-f995-11e4-99de-7b3c21ef56b5.png)

**Comment by jonpas** [comment]
You are an NCO. :grin: 

> NCO
> Unity Non-Commissioned Officers - PVT - FSGT

Note: I am not military guy, don't ask me how it is IRL and if our structure is correct. If it's wrong though, please reply and I guess we'll decide if it's intentionally wrong or not. :P

**Comment by assaultboy** [comment]
Wat? Isn't NCO reserved for SGT+?

**Comment by jonpas** [comment]
> Note: I am not military guy, don't ask me how it is IRL and if our structure is correct. If it's wrong though, please reply and I guess we'll decide if it's intentionally wrong or not. :P

AFAIK, SGT+ is Commissioned. @MattLightfoot @jezalenko @SyMP2005 help me here!

**Comment by assaultboy** [comment]
If that's how USEC is going to organzie it that's cool.
But just for a heads up the way it works in the real life is a Non-Comissioned Officer is any rank between CPL and 2LT (Not including 2LT). Commission Officers have Shinys.
Anything below CPL is just enlisted.

**Comment by codethirteen** [comment]
I made those groups up years ago and it's based on Commonwealth rank structure because that's all I knew. So LCPL to CPL was NCO, SGT and SSGT was SNCO, SGTMAJ was warrant officer, 2LT higher was Officer. Generals got General Officer / admin of forums. Each level added more moderator abilities. 

Now the ranks are more U.S.-based things have changed, we might look at fixing the forum ranks up a little.

**Comment by assaultboy** [comment]
Alright. Well I'm still a PFC so I shouldn't really be NCO either way.

**Comment by jonpas** [comment]
Hmh, I can see there is no forum user group below NCO and it's no point adding new since access would be the same (probably also the reason why it was set up like this in the first place).

I renamed the group to `Enlisted/NCO` now.

**Comment by ghost** [comment]
SGT+ is labelled Senior NCO. Blame Paul, it's his fault! :P

**Comment by jonpas** [comment]
Shush Stark, don't let me blame you!
