### ISSUE TITLE
Add Zeus role to Comreps

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#48]
For each member of a Comrep a role can be assigned. I think we should add a Zeus role for when someone is purely curating a mission.

**Comment by bonnielunawalker** [comment]
I like this idea, adds a bit more recognition to those running only Zeus
for a mission. Though I thought either Fullcom or Taccom were essentially
this?

**Comment by assaultboy** [comment]
Yeah, but from my understanding both those roles have some leadership component, whereas a Zeus role is for only running the mission.

**Comment by jonpas** [comment]
Current roles:

```
TACOM
JTAC/FO
Platoon Commander
Squad Leader
Team/Flight Leader
Team/Flight Member (Default)
```

We can expand this as we like, but of course let's try and keep it not too complicated as it's a long process to sign a COMREP in the first place.

I'd also name it "Mission Curator" rather then "Zeus", for obvious reasons. Can you put down in what order you'd like to see it (and any other roles if you want) like above?

**Comment by assaultboy** [comment]
I would probably put Curator above TACOMA. As for any other roles, I can't think of any else.

**Comment by jonpas** [comment]
Will be part of next update.

**Comment by jonpas** [comment]
Added in dev.

**Comment by ghost** [comment]
Cool, I was about to ask the same thing!
