### ISSUE TITLE
Forum Avatars Mislabeled

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#5]
On the forums the avatar names are not updated to reflect their new ranks. LCPL is labeled as PFC, PFC is labeled as PVT and PVT is labeled as RET

![Ranks](https://cloud.githubusercontent.com/assets/11630560/6807775/fbda52de-d226-11e4-8fa2-a46e3867d754.png)

**Comment by jonpas** [comment]
Already known, not sure who can change it though. I talked with Rory and I believe we agreed with just renaming them as you described.

**Comment by codethirteen** [comment]
Do we not have a forum administrator?

**Comment by MattLightfoot** [comment]
In kind basically every officer has admin to the forums and should be able to edit this. The issue we are going to have is we don't have any artwork of the single silver stripe, I'll have a look however and see what I can do unless someone beats me to it.

**Comment by jonpas** [comment]
While poking around images on the website files today (still depressed by what all I found), I saw ranks similar to SGT, but they had 3 silver stripes or something similar. I can take a look tomorrow.

**Comment by codethirteen** [comment]
Luckily I did just find a whole bunch of files for USEC, like we were talking about this morning Matt. Including the original 3DS Max file for the ranks, as well as the Photoshop PSDs for all the ranks. So if need be we can edit as required. I'll upload to Dropbox another day.

**Comment by jonpas** [comment]
!!! This is amazing, well done! On that note I believe all binary files we have regarding USEC should be stored somewhere as well, I mean somewhere as where we all can access it. Any ideas? Dropbox might work, but 2 GB limit for free accounts...

**Comment by ghost** [comment]
@codethirteen does those files include anything to do with ribbon creation?

**Comment by codethirteen** [comment]
No but I have/had a PSD I made to create new ribbons.

**Comment by ghost** [comment]
Oooh, do you still have it? It would be _very_ helpful for us creating a new ribbon for Op Anvil!

**Comment by codethirteen** [comment]
<S>I might have at home, I forgot to check last night. I'll try and remember tonight!</S>

Found the original layered ribbon PSD. Will upload it later.

**Comment by codethirteen** [comment]
http://www.mediafire.com/download/nlk40hvat554b2e/campaign.psd @jezalenko

**Comment by SyMP2005** [comment]
Nice one!

**Comment by jonpas** [comment]
@MattLightfoot if you can change it that would be best I think, at least for now as such:
- PFC -> LCPL
- PVT -> PFC
- RET -> PVT/RET (will have to do for now)

**Comment by ghost** [comment]
@codethirteen you are a life saver!!! Thankyou very much mate!

**Comment by codethirteen** [comment]
Pulled the PSD over to the private repo. @SyMP2005  @jezalenko @jonpas

**Comment by jonpas** [comment]
:+1:

**Comment by jonpas** [comment]
Fixed as per https://github.com/usecforce/USEC_Website/blob/master/profile/default.asp#L86-L102
