### ISSUE TITLE
How to disable Chronos in mission template

### ISSUE THREAD

**Issue by jelly-of-the-guava** [usecforce/USEC_IssuesWiki#6]
Probable dumb question but how do I disable Chronos in the mission template, with out breaking everything?

**Comment by DavidCamre** [comment]
Open the init.sqf file, there's a line that says
#include "CronosUSEC\chronosInit.sqf"

Simply comment that out (ie put // infront of it. That will disable chronos and the mission will run like a "normal" arma mission.

**Comment by jelly-of-the-guava** [comment]
Thanks David.

**Comment by DavidCamre** [comment]
No problem. In general for running / testing missions you shouldn't use chronos as it requires a dedicated environment with db access and a bunch of other stuff. 

For missionmaking just disable that line of code and design your mission like you normally would except don't add friendly vehicles.

**Comment by jonpas** [comment]
It should be commented out by default, is it not?

**Comment by jelly-of-the-guava** [comment]
Nope but this is me we are talking about, well I'm working with the temp, I'll make some notes that could be used for a tutorial.
