### ISSUE TITLE
Exam Issues: Recruit Exam

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#7]
I've run through a couple exams and compiled some issues here.
I'll be breaking them into separate issues for each exam as it becomes too much all at once.
# Question 6

> How often do squads conduct sessions

"sessions" Should probably be changed to "training" for clarification and to eliminate confusion

![image](https://cloud.githubusercontent.com/assets/11630560/6879144/8aa69a88-d4c3-11e4-914c-4f42b493a245.png)

**Comment by jonpas** [comment]
Changed to "training".
